In [38]:
import csv
from random import randint
import numpy as np

In [39]:
file_1 = open('Tabela_1.csv', 'w', newline='', encoding='utf-8')
file_2 = open('Tabela_2.csv', 'w', newline='', encoding='utf-8')

In [40]:
writer_1 = csv.writer(file_1)
writer_2 = csv.writer(file_2)

In [41]:
for i in range(3):
    writer_1.writerow([randint(1, 9), randint(1, 9), randint(1, 9)])
    writer_2.writerow([randint(1, 9), randint(1, 9), randint(1, 9)])
file_1.close()
file_2.close()

In [48]:
matrix_1 = np.genfromtxt('Tabela_1.csv', delimiter=',')
matrix_2 = np.genfromtxt('Tabela_2.csv', delimiter=',')

In [49]:
matrix_1


array([[1., 7., 3.],
       [1., 2., 8.],
       [4., 3., 5.]])

In [50]:
matrix_2

array([[9., 9., 2.],
       [3., 8., 5.],
       [7., 7., 1.]])

In [51]:
np.add(matrix_1, matrix_2)

array([[10., 16.,  5.],
       [ 4., 10., 13.],
       [11., 10.,  6.]])

In [52]:
np.dot(matrix_1, matrix_2)

array([[51., 86., 40.],
       [71., 81., 20.],
       [80., 95., 28.]])

In [54]:
print('Dimensao da primeira matriz: ', matrix_1.shape)
print('Dimensao da primeira matriz: ', matrix_2.shape)

Dimensao da primeira matriz:  (3, 3)
Dimensao da primeira matriz:  (3, 3)
